### ISSUE TITLE
固件是不是有问题？还是我操作有问题？

### ISSUE THREAD

**Issue by zxymdaddy** [rmoyulong/OneCloud_OpenWrt#3]
1、选用的docker 固件
[OpenWrt_immortalwrt_24.05.06_00.54.49](https://github.com/rmoyulong/OneCloud_OpenWrt/releases/tag/OpenWrt_immortalwrt_24.05.06_00.54.49)
自用玩客云[hub docker正常]固件！首次使用rufus写盘启动！
源码：immortalwrt
密码：password
地址：192.168.1.110
immortalwrt-meson-meson8b-thunder-onecloud-rootfs.tar

2、SSH 连接后提示-ash: /etc/profile.d/30-sysinfo.sh: line 25: syntax error: unexpected "(" (expecting "then")

3、opkg update 失败
ping 任何网站正常

**Comment by rmoyulong** [comment]
这个错误后续会更正

**Comment by zxymdaddy** [comment]
找到原因了。
执行：
opkg update
显示：
wget: SSL support not available, please install one of the libustream-ssl-* libraries as well as the ca-bundle and ca-certificates packages.
提示opkg依赖的wget不支持ssl/tls。

此时需要下载支持ssl/tls的wget。但是无法通过opkg下载，因为opkg需要支持ssl/tls的wget，这就陷入了无限递归的问题中。

解决方法是先手动从OpenWrt的官网下载支持ssl/tls的wget：
https://archive.openwrt.org/releases/<version>/packages/<architecture>/packages/wget-ssl_<version>_<architecture>.ipk
其中architecture可通过执行：
opkg print-architecture
命令查看。

手动下载后，通过执行：
opkg install wget-ssl_<version>_<architecture>.ipk
安装支持ssl/tls的wget。完成后，可以通过执行：
ll /usr/bin/wget
确认wget已指向新安装的wget-ssl.

**Comment by rmoyulong** [comment]
把防火墙里面所有关于Net的设置取消选取，就可以联通网络

**Comment by rmoyulong** [comment]
![捕获1](https://github.com/rmoyulong/OneCloud_OpenWrt/assets/67265640/0aa7a2f1-a6a0-41bb-a0fc-e4a50d825630)
![捕获](https://github.com/rmoyulong/OneCloud_OpenWrt/assets/67265640/f5855093-97d2-46e0-a7f5-1ffa230f584a)

**Comment by zxymdaddy** [comment]
好的。我试试。。。谢谢了
