### ISSUE TITLE
BUG。自用玩客云一站式直刷固件[amlogic6.1]！使用双USB公头线刷机！

### ISSUE THREAD

**Issue by zxymdaddy** [rmoyulong/OneCloud_OpenWrt#4]
我用的 Debian GNU/Linux 10 (buster) with Linux 5.9.0-rc7-aml-s812         docker 安装的这个固件。

1、需要安装  wget-ssl_1.24.5-r1_arm_cortex-a5_vfpv4.ipk  才能OPKG UPDATE
2、这个地址不对#src/gz immortalwrt_core https://mirrors.vsean.net/openwrt/snapshots/targets/amlogic/meson8b/packages
3、比较严重的，在没有配置任何设置怦下，只要reboot，web 192.168.1.110被拒绝，SSH一起提示密码错误，bash进入容器改密码也没有用。
4、passwall和passwall2连接速度比我原来的慢一半还多。

**Comment by rmoyulong** [comment]
正在排查

**Comment by rmoyulong** [comment]
debian 使用这个试试：
https://github.com/hzyitc/armbian-onecloud/releases/download/ci-20240311-162146-UTC/Armbian-unofficial_24.5.0-trunk_Onecloud_bookworm_edge_6.7.9_minimal.burn.img.xz

用双公头刷完armbian后，下载https://github.com/rmoyulong/OneCloud_OpenWrt/releases/download/OpenWrt__24.05.11_23.37.20/immortalwrt-meson-meson8b-thunder-onecloud-rootfs.tar.gz

把immortalwrt-meson-meson8b-thunder-onecloud-rootfs.tar.gz改名op.tar.gz
ssh armbian输入以下命令
1.ip link set eth0 promisc on
2.docker network create -d macvlan --subnet=192.168.1.0/24 --gateway=192.168.1.1 -o parent=eth0 macnet
3.docker import /home/op.tar.gz onecloud_openwrt
4.docker run -itd --name=onecloud --restart=unless-stopped --network=macnet --privileged=true onecloud_openwrt /sbin/init

**Comment by zxymdaddy** [comment]
我的使用场景是旁路由，我安装了PASSWALL2、DDNS-GO、WOLPLUS、UNBLOCKNETEASEMUSIC。昨天晚上试了一下DOCKER版的6.1和6.6，直刷没试。6.1和6.6都不能通过命令reboot和WEB界面进行重启，需要停止容器，再开始完成重启。6.1 docker run 之后第一次可以通过web进行入界面，通过DOCKER重启之后只能SSH，不能WEB登录，登录的时候会闪现一下登录界面而后出现被拒绝访问页面，应该是防火墙的问题吧。。。6.6的问题是UNBLOLCKNETEASEMUSIC防火墙规不能写入，这应该是他插件的问题。还有就是PASSWALL和PASSWALL2（我只用这两个插件上网其它没试）速度只有同设备下openwrt.ai生成的固件，passwall2速度的一半都不到，同样的配置。不知道是哪儿的问题。

**Comment by rmoyulong** [comment]
最新版本测试过已经解决

**Comment by zxymdaddy** [comment]
不错。刚才试了试，上面的问题都解决了。我再用用看看还有没有其它问题，到时候给你反馈。。

**Comment by zxymdaddy** [comment]
有个小问题咨询你一下。FW4防火墙通不过怎么回事。。脚本里面有FW4的规则但是就是通不过。
Firewall info:

Error: No such file or directory
list set inet fw4 acl_neteasemusic_http
              ^^^

Error: No such file or directory
list set inet fw4 acl_neteasemusic_https
              ^^^

Error: No such file or directory
list set inet fw4 neteasemusic
              ^^^

Error: No such file or directory
list set inet fw4 neteasemusic6
              ^^^

Error: No such file or directory
list chain inet fw4 netease_cloud_music
                ^^^

Error: No such file or directory
list chain inet fw4 netease_cloud_music_redir
                ^^^

**Comment by rmoyulong** [comment]
opkg update
opkg list luci-app-unblockneteasemusic
opkg install luci-app-unblockneteasemusic

**Comment by zxymdaddy** [comment]
这是安装之后插件日志中出现的错误。好像写入防火墙失败。

**Comment by rmoyulong** [comment]
删除核心，更新核心
